# Advocating for CRediT

*Or, how to ensure your labor is recognized and honored.*

## Learning Objective

Ensure your contributions are documented, advocate for yourself and others, and set boundaries.

## Key Terms

-   **CRediT:** A taxonomy for describing the different types of contributions that typically occur during a research project, from project conception to publication.\
-   **ORCID iD:** A unique persistent identifier to disambiguate researchers and track research outputs.

## Lesson

The reality of being in a term-limited position as a graduate student means that you may not be affiliated with the institution or lab when the project you’re on concludes. However, that does not mean that your work was not critical for completion of the project. To that end, it is important that your contributions are appropriately recognized.

This will quite obviously be tricky if you are not there to speak up–but there are practices you can start early that will benefit not only future you, but also future researchers. You can help change culture, in your lab, at your institution, and in your discipline, by ensuring your work (and the work of those who preceded you!) is documented and citable.

### Practice 1: Make an ORCID iD

One of the best – and easiest! – ways you can start receiving recognition of your work is to make an [**ORCID iD**](https://orcid.org/). These are free, persistent, and unique identifiers for researchers. In the same way that a digital object identifier (DOI) always references a single output (like an article), your ORCID will always be linked to you as you progress through your career. Creating an ORCID generates a persistent profile page for you, which will aggregate and amplify your work as well as disambiguate your research from others globally that might have a similar name.

Once you have an ORCID, you can begin entering this information when prompted, especially through publication platforms. Journals, funding agencies, and other repositories have automated connections with ORCID that will allow your research outputs to be pushed to your ORCID profile.

If needed, you can also manually update your ORCID profile page to reflect your professional achievements. This makes it easy for others to see, in one spot, all that you’ve accomplished. This is slightly different from your Google Scholar profile, as your ORCID page can capture not just your publications, but also your professional positions, committee work, and even grants received!

### Practice 2: Familiarize yourself with CRediT

Another low-entry means to start advocating for recognition of your work is to review the [**Contributor Role Taxonomy (CRediT)**](https://credit.niso.org/). This is a widely-adopted set of 14 types of contributions that typically occur during a research project, from project conception through to publication.

ACTION: [Review the different CRediT roles](https://groups.niso.org/higherlogic/ws/public/download/31067/CRediT_Taxonomy_Terms_and_Definitions_list), first by yourself and then with your PI, to clarify which role(s) you will be associated with.

Remember:

-   You can have several roles.\
-   Each role can have several assignees.

Document the results of this discussion in project documentation (e.g., the [README file](https://summermengarelli.github.io/temporal-gaps/writing-data-documentation.html)).

### Practice 3: Conceptualize the dataset as a standalone product

Often, datasets are considered the means to the end, the mechanism by which publication-ready results are produced. This understanding is (slowly) changing, as data is becoming understood as a separate and equally important output. Some disciplines are embracing the [data paper](https://www.datacc.org/en/your-needs/highlighting-your-data/publier-un-data-paper-ou-et-comment/), which is an option to highlight the work that went into creating and preparing a dataset. This is a new type of publication that is finding a home in more and more journals and may be appropriate for data that does not have access restrictions (such as sensitive data).

Also remember that data can be used outside of their original contexts! Poet Henry David Thoreau’s field notes were used by [researchers to document changes in migratory bird patterns](https://www.jstor.org/stable/44808881), providing further evidence of global warming. You may not even be able to imagine all the ways your data could be reused once it is shared.

### Practice 4: Advocate for those who preceded you

If you are the graduate student who is present as the project concludes, review the named contributors. If you know of anyone who worked on the project, in any of the roles articulated in CRediT, advocate for recognition of their labor. This is a key way to help shape and change behavior that will have an impact beyond your time with the project or lab.

Academia is small–and actions of kindness that pay it forward are welcomed and celebrated. Do not be afraid to have the hard conversations, as it can have lasting impacts for those that follow you.

### Practice 5: Set boundaries on your involvement

As you near the end of your studies, if it is clear that the project will conclude after your departure, consider carefully how you will be involved after graduation.

Consider:

-   Will you continue to work on the project to see the dataset and/or publication completed? Will you present this work?   
-   If so, is this something that will be done as part of your new role, or will this require you to volunteer your time?   
-   If this is something you will need to do outside of your daily work, consider reviewing this flowchart to decide if this is actually something you want to take on:
    -   Peltzman, S. (2016). Should You Take on a Project?: A Flowchart. Zenodo. <https://doi.org/10.5281/zenodo.4694788>
        -   Note: This ends by suggesting you CONSIDER taking on the project. That does not mean *DO* take on the project!

Whatever your decision, be sure this is understood by all parties.

And remember: even if you do not continue with the project, you still contributed, and you still deserve recognition.

## Exercise

Choose your own adventure! Select the exercise that feels right for you today–you can always come back to the other in the future.

### Elevator Pitch

A tried and true tool, an elevator pitch is a concise summary of who you are, what you are researching, and how cool that is. As a graduate student, you may have the opportunity to attend conferences and brag about your work, so be ready!\

- Spend five minutes to free write. Don’t worry about editing: focus on getting thoughts on a page.\
- Use CReDiT – what role(s) did you fill?\
- What is ONE (just one!) takeaway from your research?\
- Quick! Are you referring to the data as a standalone product?

As you continue in your education, revisit this, and keep it up to date.You may eventually have multiple versions from which you can draw.

### Data Paper Brainstorming

Let’s pretend you’re getting ready to publish your dataset, and want to publish a data paper to go alongside it. Great choice!\

- Spend five minutes pulling up every piece of documentation you have about the dataset.\
- Spend another five minutes free writing. Focus on getting an outline in place, and highlight one or two key points.\
- Now spend 15 minutes pulling in information from your various forms of documentation. Notice how much you wrote in less than half an hour!\
- Bonus! Are there sections of your paper that are missing information? Make a note if you need to update your documentation!

## Further Readings

-   [Ten Simple Rules for the Care and Feeding of Scientific Data](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003542#s1): These are some steps that anyone can take, throughout the research project, to ensure your data are ready for sharing and to capture the work of everyone involved.
