---
title: "Grad's Declassified Data Survival Guide"
author: "Summer Mengarelli and Mikala Narlock"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  #bookdown::pdf_book: default
---

# Introduction

## What is this guide?

This guide is designed for graduate students working on a research project who are tasked with managing research data. This could mean you are working in a lab, on your thesis, or something else altogether. **If you're working with data, this is for you\!** In this guide, you will find individual lessons on specific aspects of data management. These are geared towards **active** data management, meaning projects that are in process. These data are being updated, collected, aggregated, processed, cleaned, or analyzed on a regular basis. In other words, the focus of this material is how to integrate solid data management practices into your work without requiring a complete retooling of existing workflows and processes.

This guide has been published through bookdown via GitHub and can be cited as follows:

Mengarelli, S., & Narlock, M. (2025). Grad's Declassified Data Survival Guide (1.0.0-alpha). Zenodo. [https://doi.org/10.5281/zenodo.16915332](https://doi.org/10.5281/zenodo.16915332)

This guide has been written by two librarians who are also active researchers. Each author has joined existing projects and launched new ones. We have pulled on best practices from our education and lived experiences. 

## How to use this resource

While the content of each lesson varies, you will generally learn definitions, recommended practices, and tips for integrating said practices into new and existing workflows.

Each lesson is designed to be a standalone object for point of need adoption. So, when you realize you need more information about annotating code, creating a README, or keeping your data safe, you can jump right to that lesson. The lessons are ordered roughly according to a typical research lifecycle, but it is not necessary to complete prior lessons in order to understand and apply what you need.

This guide should be considered a starting point: the general recommendations may not be specific enough for your needs. In each lesson, we have provided additional resources and links to other portions of the guide. However, there are many resources available online and likely at your institution to provide the support you may need – we suggest looking into whether your institution’s library has support for research data management, or reaching out to your institutional office of research. 

All resources are only as valuable as they are to you. While we have captured and distilled recommended practices in this guide, consider which of these are useful or not in your research.

**Note**: This book is licensed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/legalcode) CC-BY.
